import { Project } from '../types';

export function exportToJson(project: Project): string {
  const payload = {
    version: '1.0',
    exportedAt: new Date().toISOString(),
    project: {
      title: project.setup.title,
      theme: project.setup.theme,
      roomStructure: project.setup.roomStructure,
      targetDuration: project.setup.targetDuration,
      difficulty: project.setup.difficulty,
      playerCount: { min: project.setup.minPlayers, max: project.setup.maxPlayers },
    },
    stages: project.stages,
    nodes: project.nodes,
    edges: project.nodes.flatMap(node =>
      node.requires.map(req => ({
        from: project.nodes.find(n => n.rewards.includes(req))?.id ?? null,
        to: node.id,
        dependency: req,
      }))
    ).filter(e => e.from !== null),
    auditResult: project.auditResult ?? null,
    integrationHints: {
      puzzleFlowVisualizer: {
        description: 'Import this JSON into Puzzle Flow Visualizer to render the dependency graph as an interactive flowchart.',
        suggestedAction: 'Use the nodes and edges arrays with @xyflow/react for node-based visualization.',
      },
      lockMapStudio: {
        description: 'Import lock nodes with answer format conflicts into LockMap Studio for mapping treatment.',
        ambiguousLocks: project.auditResult?.issues
          .filter(i => i.title.startsWith('Ambiguous Input Format'))
          .flatMap(i => i.affectedNodeIds) ?? [],
      },
    },
  };
  return JSON.stringify(payload, null, 2);
}

export function exportToMarkdown(project: Project): string {
  const audit = project.auditResult;
  const lines: string[] = [];

  lines.push(`# Dependency Audit Report: ${project.setup.title}`);
  lines.push(`**Theme:** ${project.setup.theme}`);
  lines.push(`**Structure:** ${project.setup.roomStructure} | **Difficulty:** ${project.setup.difficulty}`);
  lines.push(`**Duration:** ${project.setup.targetDuration} min | **Players:** ${project.setup.minPlayers}–${project.setup.maxPlayers}`);
  lines.push(`**Exported:** ${new Date().toLocaleString()}`);
  lines.push('');

  if (!audit) {
    lines.push('*No audit has been run for this project yet.*');
    return lines.join('\n');
  }

  lines.push('## Solvability Score');
  lines.push(`**${audit.score}/100 — ${audit.label}**`);
  lines.push('');
  lines.push(`| Severity | Count |`);
  lines.push(`|----------|-------|`);
  lines.push(`| Critical | ${audit.criticalCount} |`);
  lines.push(`| Warning  | ${audit.warningCount} |`);
  lines.push(`| Improvement | ${audit.improvementCount} |`);
  lines.push('');

  if (audit.issues.length > 0) {
    lines.push('## Issues');
    for (const issue of audit.issues) {
      lines.push(`### [${issue.severity.toUpperCase()}] ${issue.title}`);
      lines.push(`**Affected Nodes:** ${issue.affectedNodeIds.length > 0 ? issue.affectedNodeIds.join(', ') : 'N/A'}`);
      lines.push(`**Explanation:** ${issue.explanation}`);
      lines.push(`**Suggested Fix:** ${issue.suggestedFix}`);
      lines.push('');
    }
  }

  if (audit.cleanChecks.length > 0) {
    lines.push('## Passed Checks');
    for (const check of audit.cleanChecks) {
      lines.push(`- ${check}`);
    }
    lines.push('');
  }

  lines.push('## Graph Summary');
  lines.push(`- **Stages:** ${project.stages.length}`);
  lines.push(`- **Nodes:** ${project.nodes.length}`);
  lines.push(`- **Dependencies (edges):** ${project.nodes.reduce((acc, n) => acc + n.requires.length, 0)}`);
  lines.push('');
  lines.push('---');
  lines.push('*Generated by Puzzle Dependency Auditor — MJW Platform*');

  return lines.join('\n');
}
